### PR TITLE
Add config path

### PR DESCRIPTION
**Pull request by tusharmath**

### CODE REVIEW

**Comment by greghroberts** [comment]
@tusharmath  I'm considering using this library, but this issue is blocking my usage as config is a special file in my repo. Any chance of merging/releasing this soon?

**Comment by tusharmath** [comment]
The PR needs more work. I am not sure if this should even be a feature. It makes the module complicated to use 🙁

Would you consider refactoring your application instead?

**Comment by shmuel-web** [comment]
hey @tusharmath 

I used to use npm "config" and I think this is an amazing package great job
I am really in the same situation as @greghroberts 
 
please reconsider thanks

**Comment by tusharmath** [comment]
closing in favour of #22

**Pull request closed without merging**
